name: Makefile CI

on:
  push:
    branches: [ "aarch64-pe-dev" ]
  pull_request:
    branches: [ "aarch64-pe-dev" ]

jobs:
  build-aarch64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure --target=aarch64-pe --prefix="$HOME/cross"
      
    - name: build
      run: make
      
  build-all-targets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure --enable-targets=all
      
    - name: build
      run: make

  test-gmp-aarch64:

    runs-on: [self-hosted, Windows, ARM64]

    steps:
    - uses: actions/checkout@v3

    - name: Testing GMP(GCC)
      run: C:\Program` Files\Git\bin\bash.exe .github\workflows\scripts\gmp-gcc-aarch64-test.sh
