name: Makefile CI

on:
  push:
    branches: [ "aarch64-pe-dev" ]
  pull_request:
    branches: [ "aarch64-pe-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure aarch64-pe
      run: ./configure --target=aarch64-pe --prefix="$HOME/cross"
      
    - name: build
      run: make
      
#    - name: Run check
#      run: make check
      
#    - name: Run distcheck
#      run: make distcheck
