name: binutils-gdb CI

on:
  push:
    branches: [ "aarch64-pe-dev", "master" ]
  pull_request:
    branches: [ "aarch64-pe-dev" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: false
        type: string

jobs:

  build-all-targets:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: | 
        sudo apt-get update
        sudo apt-get -y install libmpfr-dev
        
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
    
    - name: configure
      run: ./configure --enable-targets=all
      
    - name: build
      run: make -j$(nproc)

  test-binutils:

    runs-on: [self-hosted, Windows, ARM64, GCC]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

    - name: Build binutils
      id: binutils-build
      run: |
        C:\Program` Files\Git\bin\bash.exe .github\workflows\scripts\build-binutils.sh

    - name: Testing OpenBLAS
      if: ${{ always() && steps.binutils-build.outcome == 'success' }}
      run: |
        C:\Program` Files\Git\bin\bash.exe .github\workflows\scripts\openblas-test.sh

    - name: Minimal console app testing
      if: ${{ always() && steps.binutils-build.outcome == 'success' }}
      run: |
        C:\Program` Files\Git\bin\bash.exe .github\workflows\scripts\min-con-app-test.sh 
    
    - name: Testing GMP(GCC)
      if: ${{ always() && steps.binutils-build.outcome == 'success' }}
      run: |
        C:\Program` Files\Git\bin\bash.exe .github\workflows\scripts\gmp-gcc-aarch64-test.sh