name: binutils-gdb CI

on:
  push:
    branches: [ "aarch64-pe-dev", "master" ]
  pull_request:
    branches: [ "aarch64-pe-dev" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: false
        type: string

jobs:
  build-all-targets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
    
    - name: configure
      run: ./configure --enable-targets=all
      
    - name: build
      run: make -j$(nproc)

  test-gmp-aarch64:

    runs-on: [self-hosted, Windows, ARM64]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

    - name: Testing GMP(GCC)
      run: |
        git checkout aarch64-pe-dev -- .github\workflows
        C:\Program` Files\Git\bin\bash.exe .github\workflows\scripts\gmp-gcc-aarch64-test.sh
