name: Makefile CI

on:
  push:
    branches: [ "aarch64-pe-dev" ]
  pull_request:
    branches: [ "aarch64-pe-dev" ]

jobs:
  build-aarch64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure --target=aarch64-pe --prefix="$HOME/cross"
      
    - name: build
      run: make
      
#    - name: Run check
#      run: make check
      
#    - name: Run distcheck
#      run: make distcheck

  build-all-targets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure --enable-targets=all
      
    - name: build
      run: make
