name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [ "aarch64-pe-dev" ]
  pull_request:
    branches: [ "aarch64-pe-dev" ]

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'


      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/bminor/binutils-gdb.git
          git fetch upstream
          git checkout origin/master
          git merge upstream/master
          git push


    
