name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [ "aarch64-pe-dev" ]
  pull_request:
    branches: [ "aarch64-pe-dev" ]

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Fork
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh repo sync Windows-on-ARM-Experiments/binutils-gdb -b master
    
