name: Sync master and build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  sync-fork:
    name: Sync master
    runs-on: ubuntu-latest

    steps:
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh repo sync Windows-on-ARM-Experiments/binutils-gdb -b master
  
  build:
    name: Build and test latest
    needs: sync-fork
    uses: ./.github/workflows/makefile.yml
    with:
      branch: ${{ github.ref }}
      merge-with-branch: master
      